#!/usr/bin/env bash
set -euo pipefail

ENV_FILE=".env"

# Bootstrap .env if it doesn't exist
if [[ ! -f "$ENV_FILE" ]]; then
  echo "[setup] No .env found — creating one with generated secrets."
  JWT_KEY=$(openssl rand -base64 48)
  SEED_PW=$(openssl rand -base64 16)
  cat >"$ENV_FILE" <<EOF
# Generated by start.sh — keep this file out of source control
JWT_KEY=${JWT_KEY}
SEED_PASSWORD=${SEED_PW}
CORS_ORIGIN=http://localhost:80
EOF
  echo "[setup] .env written. Edit CORS_ORIGIN for production deployments."
fi

# Validate required vars are present and non-empty
source "$ENV_FILE"

: "${JWT_KEY:?JWT_KEY must be set in .env}"
: "${SEED_PASSWORD:?SEED_PASSWORD must be set in .env}"

echo "[start] Building and starting containers..."
docker compose --env-file "$ENV_FILE" up --build -d

echo ""
echo "[ready] Services:"
echo "  Frontend : http://localhost:80"
echo "  Backend  : http://localhost:5001"
echo "  API docs : http://localhost:5001/swagger (development only)"
echo ""
echo "  Demo login (if seed ran):"
echo "    capturer@demo.local / (see SEED_PASSWORD in .env)"
echo "    manager@demo.local  / (see SEED_PASSWORD in .env)"
echo ""
echo "Run 'docker compose logs -f' to tail logs."
echo "Run 'docker compose down' to stop."
